CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node=1 -m train.train \
  --output_dir checkpoints/ \
  --per_device_train_batch_size 1 \
  --gradient_accumulation_steps 1 \
  --learning_rate 2e-5 \
  --weight_decay 0.05 \
  --num_train_epochs 1 \
  --lr_scheduler_type cosine \
  --warmup_ratio 0.2 \
  --save_strategy steps \
  --save_steps 1000 \
  --logging_steps 10 \
  --dataloader_num_workers 8 \
  --report_to none \
  --run_name training \
  --seed 89 \
  --lora_rank 32 \
  --lora_alpha 16 \
  --lora_dropout 0.2 \
  --use_rslora True \
  --ddp_backend nccl \
  # --model_path  
